name: CD

on:
  push:

jobs:
  run_container:
    strategy:
      fail-fast: false
      matrix:
        docker: [my-runner]
    runs-on:
      - self-hosted
      - ${{ matrix.docker }}
    container:
      image: node:16-buster-slim
      options: --cpus 1
    timeout-minutes: 10
    steps:
      - run: env
      - run: ls
      - run: pwd
      - run: echo ${{ github.runner_name }}
