name: CD

on:
  push:
    tags:
      - v*

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login GitLab
        run: |
          echo ${{ secrets.GITLAB_TOKEN }} | docker login registry.gitlab.com --username=hoge --password-stdin

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.gitlab.com/hoge/piyo
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/deploy/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  deploy:
    name: Deploy
    needs:
      - build_and_push
    runs-on: [self-hosted, my-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login GitLab
        run: |
          echo ${{ secrets.GITLAB_TOKEN }} | docker login registry.gitlab.com --username=hoge --password-stdin

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.gitlab.com/hoge/piyo
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Deploy
        env:
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          docker-compose up -d
